name: liveness_azure_flutter
description: "Simple integration with liveness azure and flutter"
version: 1.0.0
homepage: https://github.com/Bestfastfire/liveness_azure_flutter

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.10.5'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  dio: ^5.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.cleancode.liveness_azure_flutter
        pluginClass: LivenessAzureFlutterPlugin
      ios:
        pluginClass: LivenessAzureFlutterPlugin